[features]
resolution = true
skip-lint = false

[programs.devnet]
flexsoar_settlement = "CgvCAabXMe1axVCK81yAtRyNFnLM5oExtvh5K16TDcSF"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[workspace]
members = ["programs/*"]
resolver = "2"

[workspace.metadata.anchor]
address = "CgvCAabXMe1axVCK81yAtRyNFnLM5oExtvh5K16TDcSF"
